//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoLocations.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.UI.HtmlControls;
    using WebGrease.Configuration;

    public partial class Geolocation
    {
        public decimal Id { get; set; }
        public string Engineer { get; set; }
        [Required(ErrorMessage = "Enable your location")]
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Accuracy { get; set; }
        public string Equipments { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public Nullable<System.TimeSpan> CurrentTime { get; set; }

        [Required(ErrorMessage = "Select Image")]
        public HttpPostedFileBase EPhoto { get; set; }
    }
}
